inherit_from:
  - config/default.yml
  - config/rails.yml
  - config/rake.yml
  - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.0

Metrics:
  BlockLengh:
    Exclude: rubocop-presets.gemspec
