require:
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  RSpec:
    Patterns:
      - _spec.rb
      - "(?:^|/)spec/"
  RSpec/FactoryBot:
    Patterns:
      - spec/factories.rb
      - spec/factories/**/*.rb
      - features/support/factories/**/*.rb
