require:
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

RSpec:
  Include:
    - _spec.rb
    - "(?:^|/)spec/"
RSpec/FactoryBot:
  Include:
    - spec/factories.rb
    - spec/factories/**/*.rb
    - features/support/factories/**/*.rb
